id: D9755B799
source: https://library.bdrc.io
source_file: null
initial_creation_type: input
imported: '2022-06-27T04:24:43+00:00'
last_modified: '2022-06-27T10:04:32.228101+00:00'
parser: null
source_metadata:
  bdrc-instance-id: W2KG5015
  creation_method: proofreading, annotation-transfer
  source: 
      base_file: 
        id: D3871/narthang.txt  #<rkts_text_id>/<edition>
        initial_creation_type: input
      line_page_info: 
        id: IF6EAA761/I2KG212398  #<pecha_id>/<bdrc_image_group_id>
        initial_creation_type: OCR
  base:
    ADC7:
      image_group_id: I2KG212398
      title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པ་བཞུགས་སོ།
      total_pages: 75
      order: 114
      base_file: ADC7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
